# Generated by Django 4.2.7 on 2023-12-26 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_activelisting_categories_alter_user_id_comment_bid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activelisting',
            name='current_bid_user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bidder', to=settings.AUTH_USER_MODEL),
        ),
    ]
