# Generated by Django 4.2.7 on 2023-12-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_activelisting_current_bid_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activelisting',
            name='current_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
    ]
