# Generated by Django 4.2.7 on 2023-12-26 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_category_bid_created_at_comment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activelisting',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.category'),
        ),
        migrations.AlterField(
            model_name='activelisting',
            name='current_bid_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bidder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activelisting',
            name='url_photo',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='activelisting',
            name='watchlisted',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_watching', to=settings.AUTH_USER_MODEL),
        ),
    ]
